import type { TerminalCommand } from '../types'

export const terminalCommands: TerminalCommand[] = [
  {
    command: 'help',
    description: 'Lists all available commands',
    output: [
      'Available commands:',
      '',
      '  about       Whoami & bio',
      '  skills      Technical skills by category',
      '  projects    Featured projects',
      '  experience  Professional experience timeline',
      '  contact     Get in touch',
      '  education   Academic background',
      '  achievements  Awards & recognition',
      '  hobbies     Personal interests',
      '  banner      Display ASCII logo',
      '  secret      Easter egg',
      '  clear       Clear terminal',
      '',
      'Tip: Use Tab to autocomplete, Up/Down arrows for history.',
    ].join('\n'),
  },
  {
    command: 'whoami',
    description: 'Display profile info',
    output: [
      'Niranjan Kumar',
      '━━━━━━━━━━━━━━',
      'Role:      Full-Stack Developer & Blockchain Engineer',
      'Location:  India',
      '',
      'Building performant web experiences with React, TypeScript,',
      'and Solidity. Passionate about clean architecture, developer',
      'tooling, and decentralized applications.',
      '',
      '"Code is poetry, architecture is philosophy."',
    ].join('\n'),
  },
  {
    command: 'skills',
    description: 'Technical skills by category',
    output: [
      'Technical Skills',
      '━━━━━━━━━━━━━━━━',
      '',
      '  Frontend',
      '  ├─ React / Next.js / TypeScript',
      '  ├─ Tailwind CSS / Framer Motion',
      '  └─ HTML5 / CSS3 / JavaScript (ES6+)',
      '',
      '  Backend',
      '  ├─ Node.js / Express',
      '  ├─ Python / Django',
      '  └─ REST / GraphQL APIs',
      '',
      '  ML / AI',
      '  ├─ TensorFlow / PyTorch',
      '  ├─ Scikit-learn / NLP',
      '  └─ Data Analysis (Pandas, NumPy)',
      '',
      '  Databases',
      '  ├─ PostgreSQL / MongoDB',
      '  └─ Redis / Prisma ORM',
      '',
      '  DevOps & Cloud',
      '  ├─ Docker / AWS / Vercel',
      '  └─ CI/CD (GitHub Actions)',
      '',
      '  Blockchain',
      '  ├─ Solidity / Hardhat / Ethers.js',
      '  └─ Web3 / Smart Contract Development',
    ].join('\n'),
  },
  {
    command: 'projects',
    description: 'Featured projects',
    output: [
      'Featured Projects',
      '━━━━━━━━━━━━━━━━━',
      '',
      '  1.  Blockchain Voting DApp',
      '      Decentralized voting platform with gas-optimized',
      '      smart contracts and real-time result tallying.',
      '',
      '  2.  AI Content Assistant',
      '      NLP-powered content generation tool with fine-tuned',
      '      transformer models and streaming responses.',
      '',
      '  3.  DevStudio Portfolio',
      '      Interactive terminal-themed portfolio with scroll',
      '      spy navigation and typewriter animations.',
      '',
      '  4.  E-Commerce Microservices',
      '      Scalable order management with event-driven',
      '      architecture, Redis caching, and Docker orchestration.',
      '',
      'Type "contact" to see GitHub links.',
    ].join('\n'),
  },
  {
    command: 'experience',
    description: 'Work experience',
    output: [
      'Experience',
      '━━━━━━━━━━━━',
      '',
      '  2024 - Present   Full-Stack Developer @ TechCorp',
      '                    Building scalable SaaS platform serving',
      '                    50K+ users. Led migration to microservices.',
      '',
      '  2023 - 2024      Blockchain Developer @ Web3 Labs',
      '                    Developed and audited DeFi smart contracts.',
      '                    Reduced gas costs by 40% through optimization.',
      '',
      '  2022 - 2023      Frontend Engineer @ StartupXYZ',
      '                    Built component library in React + TypeScript.',
      '                    Improved Lighthouse scores from 65 to 95.',
      '',
      '  2021 - 2022      Freelance Web Developer',
      '                    Delivered 15+ client projects across',
      '                    edtech, fintech, and e-commerce domains.',
    ].join('\n'),
  },
  {
    command: 'contact',
    description: 'Contact information',
    output: [
      'Contact',
      '━━━━━━━━━',
      '',
      '  Email:    niranjan@example.com',
      '  GitHub:   https://github.com/niranjandev',
      '  LinkedIn: https://linkedin.com/in/niranjandev',
      '',
      '  Open to freelance, collaboration, and full-time',
      '  opportunities. Let\'s build something great!',
    ].join('\n'),
  },
  {
    command: 'education',
    description: 'Academic background',
    output: [
      'Education',
      '━━━━━━━━━━',
      '',
      '  B.Tech in Computer Science & Engineering',
      '  XYZ Institute of Technology (2020 - 2024)',
      '',
      '  Relevant Coursework:',
      '  ├─ Data Structures & Algorithms',
      '  ├─ Operating Systems',
      '  ├─ Database Management Systems',
      '  ├─ Computer Networks',
      '  └─ Machine Learning',
      '',
      '  CGPA: 8.7 / 10',
    ].join('\n'),
  },
  {
    command: 'achievements',
    description: 'Awards & achievements',
    output: [
      'Achievements',
      '━━━━━━━━━━━━',
      '',
      '  🏆 Winner - Blockchain Hackathon 2024',
      '  🥇 1st Place - CodeFest National Level',
      '  📄 Published Research on Smart Contract Security',
      '  🌟 Open Source Contributor (merged 20+ PRs)',
      '  🎯 Solved 500+ DSA problems across platforms',
      '  📜 Certified AWS Cloud Practitioner',
    ].join('\n'),
  },
  {
    command: 'hobbies',
    description: 'Personal interests',
    output: [
      'Hobbies & Interests',
      '━━━━━━━━━━━━━━━━━━',
      '',
      '  • Competitive Programming (Codeforces 1600+)',
      '  • Reading Sci-Fi & Tech Blogs',
      '  • Playing Chess & Strategy Games',
      '  • Photography (street & landscape)',
      '  • Building side-projects for fun',
      '  • Open source contribution',
    ].join('\n'),
  },
  {
    command: 'clear',
    description: 'Clear terminal output',
    output: '',
  },
  {
    command: 'banner',
    description: 'Display ASCII logo',
    output: [
      '╔══════════════════════════════════════╗',
      '║         ███╗   ██╗██╗██████╗        ║',
      '║         ████╗  ██║██║██╔══██╗       ║',
      '║         ██╔██╗ ██║██║██████╔╝       ║',
      '║         ██║╚██╗██║██║██╔══██╗       ║',
      '║         ██║ ╚████║██║██║  ██║       ║',
      '║         ╚═╝  ╚═══╝╚═╝╚═╝  ╚═╝       ║',
      '╚══════════════════════════════════════╝',
      '',
      '  Welcome to the terminal of Niranjan Kumar',
      '  Type "help" to explore or "secret" for a surprise.',
    ].join('\n'),
  },
  {
    command: 'secret',
    description: 'A secret easter egg',
    output: [
      '🎉 You found the secret! 🎉',
      '',
      'Fun fact: I once debugged a production issue for 8 hours',
      'straight, only to find it was a single missing semicolon.',
      'Worth every minute — learned more that day than in a week',
      'of tutorials.',
      '',
      'Here\'s a cookie: 🍪',
    ].join('\n'),
  },
]

export function getCommandOutput(input: string): string {
  const cmd = input.trim().toLowerCase()
  if (cmd === 'clear') return ''
  const found = terminalCommands.find((c) => c.command === cmd)
  if (found) return found.output
  return `bash: ${cmd}: command not found. Type 'help' for available commands.`
}
